# name: Qiita Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # derived from https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  main:
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres:9.5
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          COVER_PACKAGE: ${{ matrix.cover_package }}

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # based on https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml#L44-L72
          - 5432/tcp

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Basic dependencies install
        env:
          COVER_PACKAGE: ${{ matrix.cover_package }}
        shell: bash -l {0}
        run: |
          echo "Testing: " $COVER_PACKAGE

          # we need to download qiita directly so we have "easy" access to
          # all config files
          wget https://github.com/biocore/qiita/archive/dev.zip
          unzip dev.zip

          # pull out the port so we can modify the configuration file easily
          pgport=${{ job.services.postgres.ports[5432] }}
          sed -i "s/PORT = 5432/PORT = $pgport/" qiita-dev/qiita_core/support_files/config_test.cfg

          # PGPASSWORD is read by pg_restore, which is called by the build_db process.
          export PGPASSWORD=postgres

          # Setting up main qiita conda environment
          conda config --add channels conda-forge
          conda create -q --yes -n qiita python=3.9 libgfortran numpy nginx cython redis
          conda activate qiita
          pip install sphinx sphinx-bootstrap-theme nose-timer codecov Click

      - name: Qiita install
        shell: bash -l {0}
        run: |
          conda activate qiita
          pip install qiita-dev/ --no-binary redbiom
          mkdir ~/.qiita_plugins

      - name: Install Qiita plugins
        shell: bash -l {0}
        run: |
          conda config --add channels bioconda

          conda create -q --yes -n qtp-bam python=3.9 pip pigz quast fqtools
          conda activate qtp-bam
          export QIITA_SERVER_CERT=`pwd`/qiita-dev/qiita_core/support_files/server.crt
          export QIITA_CONFIG_FP=`pwd`/qiita-dev/qiita_core/support_files/config_test_local.cfg
          pip --quiet install -U pip
          pip install https://github.com/tedd-E/qtp-bam/archive/master.zip
          configure_qtp_bam --env-script "source /home/runner/.profile; conda activate qtp-bam" --server-cert $QIITA_SERVER_CERT

          conda create --yes -n qp-mpileup-consensus -c bioconda samtools=1.6 ivar=1.3.1 python=3.7
          conda activate qp-mpileup-consensus
          pip --quiet install .
          pip --quiet install coveralls

          export QC_REFERENCE=$PWD/qp_mpileup_consensus/support_files/references/
          for file in $(ls $QC_REFERENCE/*.gz); do gunzip $file; done

          samtools_version=`samtools --version`
          ivar_version=`ivar version`
          if [[ $samtools_version != *"1.6"* ]]; then echo "wrong samtools version", $samtools_version; exit 1; fi
          if [[ $ivar_version != *"1.3.1"* ]]; then echo "wrong ivar version", $ivar_version; exit 1; fi

          configure_qp_mpileup_consensus --env-script "source /home/runner/.profile; conda activate qp-mpileup-consensus; export QC_REFERENCE=${PWD}/qp_mpileup_consensus/support_files/references/; export ENVIRONMENT='source /home/runner/.profile; source activate qp-mpileup-consensus; export QC_REFERENCE=${PWD}/qp_mpileup_consensus/support_files/references/'" --server-cert $QIITA_SERVER_CERT

          echo "Available Qiita plugins"
          ls ~/.qiita_plugins/

      - name: Starting Main Services
        shell: bash -l {0}
        run: |
          conda activate qiita
          export QIITA_SERVER_CERT=`pwd`/qiita-dev/qiita_core/support_files/server.crt
          export QIITA_CONFIG_FP=`pwd`/qiita-dev/qiita_core/support_files/config_test_local.cfg
          sed "s#/home/runner/work/qiita/qiita#${PWD}/qiita-dev/#g" `pwd`/qiita-dev/qiita_core/support_files/config_test.cfg > ${QIITA_CONFIG_FP}

          export REDBIOM_HOST="http://localhost:7379"

          echo "1. Setting up redis"
          redis-server --daemonize yes --port 7777

          echo "2. Setting up nginx"
          mkdir -p ${CONDA_PREFIX}/var/run/nginx/
          export NGINX_FILE=`pwd`/qiita-dev/qiita_pet/nginx_example.conf
          export NGINX_FILE_NEW=`pwd`/qiita-dev/qiita_pet/nginx_example_local.conf
          sed "s#/home/runner/work/qiita/qiita#${PWD}/qiita-dev/#g" ${NGINX_FILE} > ${NGINX_FILE_NEW}
          nginx -c ${NGINX_FILE_NEW}

          echo "3. Setting up qiita"
          qiita-env make --no-load-ontologies
          qiita plugins update
          qiita-test-install

          echo "4. Starting supervisord => multiple qiita instances"
          supervisord -c ${PWD}/qiita-dev/qiita_pet/supervisor_example.conf
          sleep 10
          cat /tmp/supervisord.log

      - name: Main tests
        shell: bash -l {0}
        env:
          COVER_PACKAGE: ${{ matrix.cover_package }}
        run: |
          conda activate qp-mpileup-consensus
          export QIITA_SERVER_CERT=`pwd`/qiita-dev/qiita_core/support_files/server.crt
          export QIITA_CONFIG_FP=`pwd`/qiita-dev/qiita_core/support_files/config_test_local.cfg
          export QC_REFERENCE=$PWD/qp_mpileup_consensus/support_files/references/
          export ENVIRONMENT="source /home/runner/.profile; conda activate qp-mpileup-consensus; export QC_REFERENCE=${PWD}/qp_mpileup_consensus/support_files/references/"

          nosetests --with-doctest --with-coverage -v --cover-package=qp_mpileup_consensus

      - uses: codecov/codecov-action@v1
        with:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: codecov.yml

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: lint
      run: |
        pip install -q flake8
        flake8 qp_mpileup_consensus setup.py scripts/*
